//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marrwie.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleFile
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.Guid RowName { get; set; }
        public string MimeType { get; set; }
        public int ArticleId { get; set; }
        public string Ext { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
